// ============================================
// Job Notification Tracker - Job Dataset
// 60 Realistic Indian Tech Jobs
// ============================================

const jobsData = [
    // Internships & Fresher Roles
    {
        id: "job_001",
        title: "SDE Intern",
        company: "Amazon",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Java", "Python", "Data Structures", "Algorithms"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹25k–₹40k/month Internship",
        applyUrl: "https://amazon.jobs/en/jobs/intern-sde",
        description: "Join Amazon as a Software Development Engineer Intern. Work on real-world projects with experienced mentors. Strong coding skills required in Java or Python. Great opportunity to learn scalable system design and contribute to customer-facing products."
    },
    {
        id: "job_002",
        title: "Graduate Engineer Trainee",
        company: "Infosys",
        location: "Mysore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "SQL", "Spring Boot", "Communication"],
        source: "Naukri",
        postedDaysAgo: 0,
        salaryRange: "3.5–4.5 LPA",
        applyUrl: "https://infosys.com/careers/get",
        description: "Infosys is hiring fresh graduates for our GET program. Comprehensive training provided in full-stack development. Work on enterprise projects for global clients. Excellent learning environment with structured career growth path and mentorship opportunities."
    },
    {
        id: "job_003",
        title: "Frontend Intern",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        skills: ["React", "JavaScript", "HTML", "CSS", "Git"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹30k–₹50k/month Internship",
        description: "Build beautiful payment interfaces used by millions. Work with modern React ecosystem and learn from senior engineers. Fast-paced fintech environment with opportunity for full-time conversion. Strong JavaScript fundamentals required."
    },
    {
        id: "job_004",
        title: "QA Intern",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Manual Testing", "Selenium", "Java", "API Testing"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "₹20k–₹35k/month Internship",
        description: "Join Flipkart's Quality Assurance team. Learn automated testing frameworks and work on India's largest e-commerce platform. Hands-on experience with Selenium, API testing, and CI/CD pipelines. Mentorship from experienced QA professionals."
    },
    {
        id: "job_005",
        title: "Data Analyst Intern",
        company: "Swiggy",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Python", "SQL", "Excel", "Data Visualization", "Statistics"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹25k–₹40k/month Internship",
        description: "Analyze food delivery data and generate insights. Work with large datasets using Python and SQL. Create dashboards and reports for business teams. Great opportunity to learn data analytics in a fast-growing startup environment."
    },

    // 0-1 Year Experience
    {
        id: "job_006",
        title: "Java Developer",
        company: "TCS",
        location: "Pune",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java", "Spring Boot", "MySQL", "REST APIs"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "4–6 LPA",
        description: "Develop enterprise Java applications for banking clients. Work with Spring Boot and microservices architecture. Collaborative team environment with opportunities to learn from senior developers. TCS offers excellent work-life balance and career growth."
    },
    {
        id: "job_007",
        title: "Python Developer",
        company: "Wipro",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Python", "Django", "PostgreSQL", "Docker"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "4.5–6.5 LPA",
        description: "Build backend services using Python and Django. Work on automation and data processing projects. Exposure to cloud technologies and containerization. Great learning opportunities in a supportive team environment."
    },
    {
        id: "job_008",
        title: "React Developer",
        company: "Zoho",
        location: "Chennai",
        mode: "Onsite",
        experience: "0-1",
        skills: ["React", "JavaScript", "Redux", "TypeScript"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "5–7 LPA",
        description: "Join Zoho's product development team. Build modern web applications using React and TypeScript. Work on products used by millions globally. Excellent product company culture with focus on innovation and quality code."
    },
    {
        id: "job_009",
        title: "Backend Developer",
        company: "PhonePe",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java", "Spring Boot", "Kafka", "Redis", "MySQL"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "8–12 LPA",
        description: "Build scalable backend systems for India's leading payment platform. Work with high-traffic systems processing millions of transactions. Learn distributed systems, caching, and message queues. Fast-paced fintech environment with great compensation."
    },
    {
        id: "job_010",
        title: "Full Stack Developer",
        company: "Freshworks",
        location: "Chennai",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["React", "Node.js", "MongoDB", "Express"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "6–9 LPA",
        description: "Develop SaaS products used by businesses worldwide. Work across the full stack with modern technologies. Collaborative environment with focus on clean code and best practices. Great opportunity to grow in a product company."
    },

    // 1-3 Years Experience
    {
        id: "job_011",
        title: "Senior Frontend Developer",
        company: "CRED",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React", "TypeScript", "Next.js", "GraphQL"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "15–25 LPA",
        description: "Build premium user experiences for CRED's fintech products. Work with cutting-edge frontend technologies. High-quality codebase with focus on performance and design. Competitive compensation and ESOP benefits."
    },
    {
        id: "job_012",
        title: "DevOps Engineer",
        company: "Paytm",
        location: "Noida",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["AWS", "Kubernetes", "Docker", "Jenkins", "Terraform"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "10–16 LPA",
        description: "Manage cloud infrastructure for India's largest digital payments company. Automate deployments and ensure high availability. Work with modern DevOps tools and practices. Great exposure to large-scale distributed systems."
    },
    {
        id: "job_013",
        title: "Mobile Developer - Android",
        company: "Juspay",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Kotlin", "Android SDK", "MVVM", "Jetpack Compose"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "12–18 LPA",
        description: "Develop payment SDKs used by major e-commerce platforms. Work on cutting-edge Android development with Kotlin and Jetpack Compose. High-impact work affecting millions of users. Strong engineering culture with focus on quality."
    },
    {
        id: "job_014",
        title: "Data Engineer",
        company: "Accenture",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Python", "Spark", "Airflow", "AWS", "SQL"],
        source: "Indeed",
        postedDaysAgo: 6,
        salaryRange: "8–12 LPA",
        description: "Build data pipelines for enterprise clients. Work with big data technologies like Spark and Airflow. Exposure to cloud platforms and modern data engineering practices. Work on diverse projects across industries."
    },
    {
        id: "job_015",
        title: "Backend Engineer",
        company: "Capgemini",
        location: "Mumbai",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Node.js", "Express", "MongoDB", "Microservices"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "7–11 LPA",
        description: "Develop microservices for global clients. Work with Node.js and modern backend technologies. Collaborative international teams with exposure to various domains. Good work-life balance and learning opportunities."
    },

    // More Companies - Cognizant
    {
        id: "job_016",
        title: "Java Full Stack Developer",
        company: "Cognizant",
        location: "Chennai",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Java", "Spring Boot", "Angular", "MySQL"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "6–10 LPA",
        description: "Work on full-stack enterprise applications. Develop both frontend and backend components. Exposure to Agile methodologies and client interactions. Structured career progression with training opportunities."
    },

    // IBM
    {
        id: "job_017",
        title: "Cloud Engineer",
        company: "IBM",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["IBM Cloud", "Kubernetes", "Python", "Terraform"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "9–14 LPA",
        description: "Design and implement cloud solutions on IBM Cloud platform. Work with enterprise clients on cloud migration projects. Learn cutting-edge cloud technologies and earn certifications. Global exposure and career growth opportunities."
    },

    // Oracle
    {
        id: "job_018",
        title: "Database Developer",
        company: "Oracle",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Oracle DB", "PL/SQL", "Performance Tuning", "SQL"],
        source: "Indeed",
        postedDaysAgo: 7,
        salaryRange: "8–13 LPA",
        description: "Optimize and maintain Oracle databases for enterprise clients. Work on performance tuning and query optimization. Deep technical learning in database technologies. Work with experienced DBAs and architects."
    },

    // SAP
    {
        id: "job_019",
        title: "SAP ABAP Developer",
        company: "SAP",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["ABAP", "SAP HANA", "OOPS", "SAP Fiori"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "7–12 LPA",
        description: "Develop SAP applications using ABAP programming. Work on SAP HANA and Fiori technologies. High demand skillset with excellent career prospects. Work with global teams on enterprise solutions."
    },

    // Dell
    {
        id: "job_020",
        title: "Software Engineer",
        company: "Dell",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["C++", "Python", "Linux", "Networking"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "8–12 LPA",
        description: "Work on Dell's infrastructure software products. Develop system-level applications and tools. Exposure to hardware-software integration. Great work culture with focus on innovation and employee development."
    },

    // Startups
    {
        id: "job_021",
        title: "Full Stack Developer",
        company: "Meesho",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React", "Node.js", "PostgreSQL", "Redis"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "12–20 LPA",
        description: "Build features for India's fastest-growing social commerce platform. Work on high-impact projects affecting millions of resellers. Modern tech stack with emphasis on scalability. Startup culture with great learning and ESOP benefits."
    },
    {
        id: "job_022",
        title: "Backend Developer",
        company: "Dunzo",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Python", "Django", "PostgreSQL", "AWS"],
        source: "Indeed",
        postedDaysAgo: 4,
        salaryRange: "10–16 LPA",
        description: "Develop backend services for quick commerce platform. Work on real-time order processing and logistics optimization. Fast-paced startup environment with ownership and impact. Learn scalable system design."
    },
    {
        id: "job_023",
        title: "Frontend Engineer",
        company: "Groww",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React", "TypeScript", "Redux", "Webpack"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "14–22 LPA",
        description: "Build investment platform used by millions of Indians. Create intuitive UIs for complex financial products. High-quality codebase with focus on performance. Fintech startup with excellent compensation and growth."
    },
    {
        id: "job_024",
        title: "ML Engineer",
        company: "Ola",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Python", "TensorFlow", "PyTorch", "ML Algorithms"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "12–18 LPA",
        description: "Work on machine learning models for ride optimization and pricing. Apply ML to real-world transportation problems. Access to large datasets and production ML systems. Great opportunity to work on impactful AI projects."
    },
    {
        id: "job_025",
        title: "iOS Developer",
        company: "Zomato",
        location: "Gurgaon",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Swift", "iOS SDK", "SwiftUI", "Core Data"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "11–17 LPA",
        description: "Develop Zomato's iOS app used by millions for food delivery. Work with modern Swift and SwiftUI. High-performance requirements with focus on user experience. Foodtech leader with strong engineering culture."
    },

    // 3-5 Years Experience
    {
        id: "job_026",
        title: "Senior Backend Engineer",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Onsite",
        experience: "3-5",
        skills: ["Java", "Spring Boot", "Kafka", "PostgreSQL", "Redis"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "25–40 LPA",
        description: "Lead backend development for payment processing systems. Design scalable microservices handling millions of transactions. Mentor junior engineers and drive technical decisions. Fintech unicorn with excellent compensation and ESOPs."
    },
    {
        id: "job_027",
        title: "Tech Lead - Frontend",
        company: "PhonePe",
        location: "Bangalore",
        mode: "Onsite",
        experience: "3-5",
        skills: ["React", "TypeScript", "Micro-frontends", "System Design"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "30–50 LPA",
        description: "Lead frontend architecture for payment products. Build scalable micro-frontend systems. Mentor team of engineers and drive technical excellence. Work on products used by 400M+ users. Competitive compensation package."
    },
    {
        id: "job_028",
        title: "Senior SDE",
        company: "Amazon",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["Java", "AWS", "Distributed Systems", "System Design"],
        source: "Indeed",
        postedDaysAgo: 0,
        salaryRange: "35–55 LPA",
        description: "Design and build large-scale distributed systems. Work on Amazon's core infrastructure services. Ownership of critical systems affecting millions of customers. World-class engineering culture with focus on innovation and customer obsession."
    },
    {
        id: "job_029",
        title: "Senior Full Stack Engineer",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Onsite",
        experience: "3-5",
        skills: ["React", "Java", "Spring Boot", "MySQL", "Redis"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "28–45 LPA",
        description: "Build end-to-end features for e-commerce platform. Work across frontend and backend with modern technologies. High-impact work on systems serving millions daily. Great compensation with ESOP benefits."
    },
    {
        id: "job_030",
        title: "Staff Engineer",
        company: "Swiggy",
        location: "Bangalore",
        mode: "Onsite",
        experience: "3-5",
        skills: ["System Design", "Microservices", "Kafka", "PostgreSQL"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "32–50 LPA",
        description: "Drive technical strategy for food delivery platform. Design scalable systems for real-time order processing. Lead multiple teams and influence engineering culture. Foodtech unicorn with strong growth trajectory."
    },

    // More Diverse Roles
    {
        id: "job_031",
        title: "Junior Backend Developer",
        company: "Nykaa",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Python", "Flask", "MongoDB", "REST APIs"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "5–8 LPA",
        description: "Develop backend services for beauty e-commerce platform. Work with Python and modern web frameworks. Learn from experienced engineers in a product company. Great opportunity in growing beauty-tech sector."
    },
    {
        id: "job_032",
        title: "React Native Developer",
        company: "Urban Company",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React Native", "JavaScript", "Redux", "Mobile Development"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "10–15 LPA",
        description: "Build cross-platform mobile apps for home services platform. Work on features used by millions of customers and service professionals. Modern mobile development practices with focus on performance. Fast-growing startup with impact."
    },
    {
        id: "job_033",
        title: "QA Automation Engineer",
        company: "Myntra",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Selenium", "Java", "TestNG", "API Testing", "CI/CD"],
        source: "Indeed",
        postedDaysAgo: 6,
        salaryRange: "8–13 LPA",
        description: "Automate testing for fashion e-commerce platform. Build robust test frameworks and ensure quality. Work with modern testing tools and practices. Part of Flipkart group with excellent benefits."
    },
    {
        id: "job_034",
        title: "Security Engineer",
        company: "Paytm",
        location: "Noida",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Security", "Penetration Testing", "Python", "Network Security"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "10–16 LPA",
        description: "Ensure security of payment systems and user data. Conduct security audits and penetration testing. Work with security tools and best practices. Critical role in fintech with high responsibility."
    },
    {
        id: "job_035",
        title: "Data Scientist",
        company: "Ola",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Python", "Machine Learning", "Statistics", "SQL", "Pandas"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "12–20 LPA",
        description: "Build predictive models for ride demand and pricing. Work with large-scale transportation data. Apply statistical methods to business problems. Great opportunity in data science with real-world impact."
    },
    {
        id: "job_036",
        title: "Product Engineer",
        company: "Postman",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["JavaScript", "Node.js", "Electron", "React"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "15–25 LPA",
        description: "Build API development tools used by millions of developers worldwide. Work on Postman's desktop and web applications. Remote-first company with global team. Developer tools company with strong engineering culture."
    },
    {
        id: "job_037",
        title: "SRE Engineer",
        company: "Zomato",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Linux", "Kubernetes", "Monitoring", "Python", "AWS"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "12–18 LPA",
        description: "Ensure reliability and performance of food delivery platform. Monitor systems and respond to incidents. Automate operations and improve infrastructure. Learn SRE practices at scale."
    },
    {
        id: "job_038",
        title: "Blockchain Developer",
        company: "Polygon",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["Solidity", "Ethereum", "Web3.js", "Smart Contracts"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "18–30 LPA",
        description: "Develop blockchain solutions on Polygon network. Build and audit smart contracts. Work on cutting-edge Web3 technologies. Crypto unicorn with global impact and competitive compensation."
    },
    {
        id: "job_039",
        title: "UI/UX Engineer",
        company: "CRED",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React", "CSS", "Design Systems", "Figma", "Animation"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "14–22 LPA",
        description: "Create premium user experiences with focus on design and interaction. Implement design systems and animations. Work closely with designers. Known for best-in-class UI/UX in Indian fintech."
    },
    {
        id: "job_040",
        title: "Backend Engineer - Go",
        company: "Zerodha",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Golang", "PostgreSQL", "Redis", "Microservices"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "15–25 LPA",
        description: "Build trading platform backend using Go. Work on high-performance, low-latency systems. India's largest stockbroker with focus on technology. Profitable company with excellent work culture."
    },

    // Additional Fresher Roles
    {
        id: "job_041",
        title: "Graduate Trainee - Software",
        company: "HCL Technologies",
        location: "Noida",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "C++", "SQL", "Problem Solving"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "3.2–4 LPA",
        description: "Join HCL's graduate training program. Comprehensive training in software development. Work on client projects across domains. Structured learning path with certifications and mentorship."
    },
    {
        id: "job_042",
        title: "Associate Software Engineer",
        company: "Tech Mahindra",
        location: "Pune",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Java", "Python", "JavaScript", "Agile"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "3.5–4.5 LPA",
        description: "Start your career with Tech Mahindra. Work on telecom and enterprise projects. Training provided in latest technologies. Good work-life balance with career growth opportunities."
    },
    {
        id: "job_043",
        title: "Junior Software Developer",
        company: "Mindtree",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["JavaScript", "React", "Node.js", "MongoDB"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "4.5–6 LPA",
        description: "Develop web applications for global clients. Work with modern JavaScript stack. Collaborative environment with focus on innovation. Part of L&T group with stability and growth."
    },
    {
        id: "job_044",
        title: "Software Engineer Trainee",
        company: "Mphasis",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Java", "Spring", "MySQL", "REST APIs"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "3.8–4.8 LPA",
        description: "Join Mphasis as a trainee software engineer. Work on banking and financial services projects. Structured training program with hands-on experience. Good exposure to enterprise technologies."
    },
    {
        id: "job_045",
        title: "Junior QA Engineer",
        company: "LTI",
        location: "Mumbai",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Manual Testing", "Selenium", "JIRA", "Test Cases"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "3.5–5 LPA",
        description: "Quality assurance role for enterprise applications. Learn testing methodologies and automation. Work with experienced QA teams. Good starting point for QA career."
    },

    // More Mid-Level Roles
    {
        id: "job_046",
        title: "Full Stack Engineer",
        company: "ShareChat",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React", "Python", "Django", "PostgreSQL", "Redis"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "12–18 LPA",
        description: "Build features for India's largest social media platform. Work on systems serving 180M+ users. Modern tech stack with focus on scale and performance. Social media startup with strong growth."
    },
    {
        id: "job_047",
        title: "Android Developer",
        company: "Dream11",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Kotlin", "Android", "MVVM", "Retrofit", "Room"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "10–16 LPA",
        description: "Develop fantasy sports app used by millions. Work with modern Android development practices. High-performance requirements for real-time features. Gaming startup with exciting challenges."
    },
    {
        id: "job_048",
        title: "Backend Developer - Python",
        company: "Udaan",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Python", "FastAPI", "PostgreSQL", "Microservices"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "11–17 LPA",
        description: "Build B2B e-commerce platform for small businesses. Work on inventory and logistics systems. Impactful work helping digitize Indian businesses. Unicorn startup with strong engineering culture."
    },
    {
        id: "job_049",
        title: "Frontend Developer",
        company: "Licious",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React", "Next.js", "TypeScript", "GraphQL"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "9–14 LPA",
        description: "Build e-commerce platform for fresh meat and seafood. Work with modern frontend stack. Focus on user experience and performance. D2C startup in growing sector."
    },
    {
        id: "job_050",
        title: "DevOps Engineer",
        company: "Cure.fit",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["AWS", "Docker", "Kubernetes", "Jenkins", "Python"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "10–15 LPA",
        description: "Manage infrastructure for health and fitness platform. Automate deployments and monitoring. Work with cloud-native technologies. Health-tech startup with mission-driven culture."
    },

    // Senior Roles
    {
        id: "job_051",
        title: "Senior Software Engineer",
        company: "Microsoft",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["C#", ".NET", "Azure", "Microservices", "System Design"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "40–65 LPA",
        description: "Work on Microsoft's cloud and enterprise products. Design scalable distributed systems. Collaborate with global teams. World-class engineering environment with cutting-edge technologies and excellent compensation."
    },
    {
        id: "job_052",
        title: "Principal Engineer",
        company: "Google",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["System Design", "Distributed Systems", "C++", "Python"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "50–80 LPA",
        description: "Lead technical initiatives for Google products. Design systems at massive scale. Mentor engineers and drive technical excellence. Work on products used by billions globally. Top-tier compensation and benefits."
    },
    {
        id: "job_053",
        title: "Engineering Manager",
        company: "Uber",
        location: "Bangalore",
        mode: "Onsite",
        experience: "3-5",
        skills: ["Leadership", "System Design", "Java", "Microservices"],
        source: "Indeed",
        postedDaysAgo: 4,
        salaryRange: "45–70 LPA",
        description: "Lead engineering team building ride-sharing platform. Manage technical roadmap and team growth. Work on high-scale distributed systems. Global company with strong engineering culture."
    },
    {
        id: "job_054",
        title: "Architect - Cloud Solutions",
        company: "Adobe",
        location: "Noida",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["AWS", "System Architecture", "Microservices", "Java"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "38–60 LPA",
        description: "Design cloud architecture for Adobe's creative products. Lead technical strategy and implementation. Work with cutting-edge technologies. Product company with focus on innovation and quality."
    },
    {
        id: "job_055",
        title: "Lead Developer",
        company: "Salesforce",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["Java", "Salesforce", "Apex", "Lightning", "System Design"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "35–55 LPA",
        description: "Lead development of CRM solutions. Work on Salesforce platform and custom applications. Mentor team and drive technical decisions. Enterprise software leader with excellent benefits."
    },

    // Additional Diverse Roles
    {
        id: "job_056",
        title: "Performance Engineer",
        company: "Hotstar",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Performance Testing", "JMeter", "Python", "Monitoring"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "10–16 LPA",
        description: "Ensure performance of video streaming platform. Test systems handling millions of concurrent users. Work on optimization and monitoring. OTT leader with interesting technical challenges."
    },
    {
        id: "job_057",
        title: "Game Developer",
        company: "Games24x7",
        location: "Mumbai",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Unity", "C#", "Game Development", "3D Graphics"],
        source: "Indeed",
        postedDaysAgo: 6,
        salaryRange: "8–14 LPA",
        description: "Develop mobile games for RummyCircle and My11Circle. Work with Unity and game development tools. Creative and technical challenges. Gaming company with fun work culture."
    },
    {
        id: "job_058",
        title: "AI/ML Engineer",
        company: "Fractal Analytics",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Python", "TensorFlow", "NLP", "Computer Vision"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "12–20 LPA",
        description: "Build AI solutions for Fortune 500 clients. Work on NLP and computer vision projects. Exposure to diverse AI applications. Analytics company with focus on cutting-edge AI."
    },
    {
        id: "job_059",
        title: "Embedded Software Engineer",
        company: "Bosch",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["C", "Embedded C", "RTOS", "Microcontrollers"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "7–12 LPA",
        description: "Develop embedded software for automotive systems. Work with microcontrollers and RTOS. Hardware-software integration experience. Global engineering company with strong R&D focus."
    },
    {
        id: "job_060",
        title: "Site Reliability Engineer",
        company: "LinkedIn",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Linux", "Python", "Kubernetes", "Monitoring", "Automation"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "18–28 LPA",
        description: "Ensure reliability of LinkedIn's infrastructure. Build automation and monitoring systems. Work on large-scale distributed systems. Professional network leader with excellent engineering culture and compensation."
    }
];

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = jobsData;
}
